// <auto-generated />
namespace iep_projekat_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_enum_state : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_enum_state));
        
        string IMigrationMetadata.Id
        {
            get { return "201607082201306_add_enum_state"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
