// <auto-generated />
namespace iep_projekat_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modelsauctionorderbid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelsauctionorderbid));
        
        string IMigrationMetadata.Id
        {
            get { return "201607082102158_models auction order bid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
